# Copyright 2022 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

{
    "name": "Brand stock account",
    "summary": "When the account entry is generated by the stock move, fill also the brand.",
    "version": "13.0.1.0.1",
    "category": "Accounting Management",
    "website": "https://github.com/OCA/brand",
    "author": "ACSONE SA/NV," "Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "depends": ["sale_brand", "stock_account", "account_brand"],
    "data": [],
    "installable": True,
    "development_status": "Beta",
}
