[project]
name = "odoo-addons-oca-brand"
version = "19.0.20260923.2"
dependencies = [
    "odoo-addon-account_brand==19.0.*",
    "odoo-addon-brand==19.0.*",
    "odoo-addon-brand_external_report_layout==19.0.*",
    "odoo-addon-partner_brand==19.0.*",
    "odoo-addon-pricelist_brand==19.0.*",
    "odoo-addon-product_brand==19.0.*",
    "odoo-addon-product_brand_mrp==19.0.*",
    "odoo-addon-product_brand_purchase==19.0.*",
    "odoo-addon-product_brand_stock==19.0.*",
    "odoo-addon-product_brand_stock_account==19.0.*",
    "odoo-addon-product_brand_tag==19.0.*",
    "odoo-addon-sale_brand==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
